services:
  web:
    build: .
    container_name: flask_app
    command: flask run --host=0.0.0.0 --port=5000 --reload
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - FLASK_APP=backend/app.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/car_db
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

 